//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnSpy.StringSearcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dnSpy_StringSearcher_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dnSpy_StringSearcher_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dnSpy.StringSearcher.Properties.dnSpy.StringSearcher.Resources", typeof(dnSpy_StringSearcher_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literal.
        /// </summary>
        public static string ColumnLiteral {
            get {
                return ResourceManager.GetString("ColumnLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string ColumnMethod {
            get {
                return ResourceManager.GetString("ColumnMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string ColumnModule {
            get {
                return ResourceManager.GetString("ColumnModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy String Literal (Raw).
        /// </summary>
        public static string CopyRawStringLiteralCommand {
            get {
                return ResourceManager.GetString("CopyRawStringLiteralCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy String Literal (Formatted).
        /// </summary>
        public static string CopyStringLiteralCommand {
            get {
                return ResourceManager.GetString("CopyStringLiteralCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dbl Click.
        /// </summary>
        public static string DoubleClick {
            get {
                return ResourceManager.GetString("DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find String References in Module.
        /// </summary>
        public static string FindStringReferencesInModuleCommand {
            get {
                return ResourceManager.GetString("FindStringReferencesInModuleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Reference in Method.
        /// </summary>
        public static string GoToReferenceInCodeCommand {
            get {
                return ResourceManager.GetString("GoToReferenceInCodeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Reference in Method (New Tab).
        /// </summary>
        public static string GoToReferenceInCodeNewTabCommand {
            get {
                return ResourceManager.GetString("GoToReferenceInCodeNewTabCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross References Strings in Modules.
        /// </summary>
        public static string PluginShortDescription {
            get {
                return ResourceManager.GetString("PluginShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ReferencesRefresh {
            get {
                return ResourceManager.GetString("ReferencesRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ReferencesSearch {
            get {
                return ResourceManager.GetString("ReferencesSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+C.
        /// </summary>
        public static string ShortCutKeyCtrlC {
            get {
                return ResourceManager.GetString("ShortCutKeyCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String References.
        /// </summary>
        public static string StringReferencesWindowTitle {
            get {
                return ResourceManager.GetString("StringReferencesWindowTitle", resourceCulture);
            }
        }
    }
}
